//Names Action Types
export const REQUEST_NAMES = 'REQUEST_NAMES';
export const RECEIVE_NAMES = 'RECEIVE_NAMES';
export const RECEIVE_NAMES_ERROR = 'RECEIVE_NAMES_ERROR';

export const REQUEST_PROFILE = 'REQUEST_PROFILE';
export const RECEIVE_PROFILE = 'RECEIVE_PROFILE';
export const RECEIVE_PROFILE_ERROR = 'RECEIVE_PROFILE_ERROR';

export const ADD_NAME_REQUEST = 'ADD_NAME_REQUEST';
export const ADD_NAME_SUCCESS = 'ADD_NAME_SUCCESS';

export const FILTER_NAMES = 'FILTER_NAMES';
export const DELETE_NAME = 'DELETE_NAME';


//Products Action Types
export const REQUEST_PRODUCTS = 'REQUEST_PRODUCTS';
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS';
export const RECEIVE_PRODUCTS_ERROR = 'RECEIVE_PRODUCTS_ERROR';

export const REQUEST_PRODUCT_PROFILE = 'REQUEST_PRODUCT_PROFILE';
export const RECEIVE_PRODUCT_PROFILE = 'RECEIVE_PRODUCT_PROFILE';
export const RECEIVE_PRODUCT_ERROR = 'RECEIVE_PRODUCT_ERROR';


//Reviews Action Types
export const REQUEST_REVIEWS = 'REQUEST_REVIEWS';
export const RECEIVE_REVIEWS = 'RECEIVE_REVIEWS';

export const REQUEST_ADD_REVIEW = 'REQUEST_ADD_REVIEW';
export const SUCCESS_ADD_REVIEW = 'SUCCESS_ADD_REVIEW';


export const CLEAR_ERROR = 'CLEAR_ERROR';